# Generated by Django 5.1.6 on 2025-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_doctor",
            field=models.BooleanField(default=False),
        ),
    ]
